name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18.8.0'
          cache: 'npm'
          cache-dependency-path: './solid/package-lock.json'
      
      - name: Build frontend
        run: |
          npm ci --no-optional
          npm run build
        working-directory: ./solid

      - name: Copy to dist folder
        run: |
          mkdir -p dist/solid
          cp -r deno/* dist/
          cp -r solid/dist/* dist/solid/

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "webplatformz-ur-game"
          entrypoint: "./server.js"
          root: dist
